services:
    web:
        build: .
        ports:
            - 5173:5173
            - 3000:3000
        develop:
            watch:
                - path: ./package.json
                  action: rebuild
                - path: ./yarn.lock
                  action: rebuild
                - path: ./
                  target: /app
                  ignore:
                      - ./node_modules
                  action: sync
